# Generated by Django 4.2.5 on 2023-10-01 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BancoLibrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Moneda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=10)),
                ('Simbolo', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='ChRecibidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaEmision', models.DateField()),
                ('fechaCobro', models.DateField()),
                ('serie', models.IntegerField()),
                ('numero', models.IntegerField()),
                ('cliente', models.CharField(max_length=60)),
                ('Moneda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ControlApp.moneda')),
                ('bancoLibrador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ControlApp.bancolibrador')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ControlApp.estado')),
            ],
        ),
        migrations.CreateModel(
            name='ChEmitidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FechaEmision', models.DateField()),
                ('FechaPago', models.DateField()),
                ('Serie', models.IntegerField()),
                ('Numero', models.IntegerField()),
                ('Proveedor', models.CharField(max_length=60)),
                ('BancoLibrador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ControlApp.bancolibrador')),
                ('Moneda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ControlApp.moneda')),
            ],
        ),
    ]
